config/routes.rb
Rails.application.routes.draw do
  devise_for  :users

  namespace 'admin' do
    resources 'ambassadorships'
    resources 'cities' do
      member do
        get 'ambassadors'
        get 'guests'
        get 'hosts'
        get 'preregistrations'
      end
    end
    resources 'users' do
      collection do
        get 'admins'
        get 'ambassadors'
        get 'hosts'
        get 'guests'
        get 'search'
      end
    end
    get 'preregistrations' => 'preregistrations#index'
    post 'preregistrations' => 'preregistrations#import'
    root to: 'dashboard#index'
  end

  namespace 'my' do
    get 'messages' => 'messages#index'
    get 'messages/:user_slug' => 'messages#user', as: :conversation
    post 'messages/:user_slug' => 'messages#create', as: :send_message
    get 'profile' => 'profile#index'
    put 'profile' => 'profile#update'
    get 'reviews' => 'reviews#index'
    post 'reviews/:user_slug' => 'reviews#save', as: :review
    patch 'reviews/:user_slug' => 'reviews#save'
    resources 'meals'
    root to: 'dashboard#index'
  end

  namespace 'my_cities' do
    scope ':city_slug' do
      scope 'users' do
        get 'approval' => 'users#approval', as: :users_approval
        get 'hosts' => 'users#hosts', as: :users_hosts
        post ':user_slug/approve' => 'users#approve', as: :user_approve
        post ':user_slug/unapprove' => 'users#unapprove', as: :user_unapprove
        root to: 'users#index', as: :users
      end
      scope 'reviews' do
        get 'approval' => 'reviews#approval', as: :reviews_approval
        post ':id/approve' => 'reviews#approve', as: :review_approve
        post ':id/unapprove' => 'reviews#unapprove', as: :review_unapprove
        root to: 'reviews#index', as: :reviews
      end
    end
    root to: 'application#index'
  end

  post 'preregistrations' => 'preregistrations#create'
  get 'users/:user_slug' => 'users#show', as: :user
  get 'hosts' => 'hosts#index'
  get 'hosts/:city_slug' => 'hosts#city', as: :city_hosts
  get 'ambassadors' => 'ambassadors#index'
  get 'press' => 'pages#press'
  get 'who' => 'pages#who'
  get 'legal' => 'pages#legal'
  root to: 'pages#index'
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id          :bigint(8)        not null, primary key
#  date        :datetime
#  host_id     :bigint(8)
#  capacity    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  confirmed   :integer          default(1)
#  remaining   :integer
#  description :text
#  formula     :integer
#

class Meal < ApplicationRecord
  enum formula: { 
    main: 0, 
    starter_main: 1, 
    main_dessert: 2, 
    starter_main_dessert: 3
  } 

  belongs_to :host, class_name: "User"

  validates_presence_of :date, :capacity, :confirmed
  validates :capacity, numericality: { greater_than_or_equal_to: 1 }
  validates :confirmed, numericality: { less_than_or_equal_to: :capacity, greater_than_or_equal_to: 0 }
  validate :date_cannot_be_in_the_past

  scope :future, -> { where('date >= ?', Date.today) }
  scope :not_full, -> { where('remaining > 0') }
  scope :opened, -> { future.not_full }

  before_validation :denormalize_remaining

  protected

  def denormalize_remaining
    self.remaining = self.capacity.to_i - self.confirmed.to_i
  end

  def date_cannot_be_in_the_past
    if date.present? && date.past?
      errors.add(:date, "ne peut pas être déjà passée")
    end
  end
end

app/controllers/my/application_controller.rb
class My::ApplicationController < ApplicationController
  add_breadcrumb I18n.t('my.name'), :my_root_path

  before_action :authenticate_user!
end

app/controllers/my/dashboard_controller.rb
class My::DashboardController < My::ApplicationController
  def index
  end
end

app/controllers/my/meals_controller.rb
class My::MealsController < My::ApplicationController
  load_and_authorize_resource

  add_breadcrumb I18n.t('my.meals.name'), :my_meals_path

  def index
    @meals = current_user.meals.future
  end

  def new
    add_breadcrumb t('my.meals.new')
    @meal = Meal.new capacity: 2, confirmed: 1, date: Date.tomorrow
  end

  def edit
    add_breadcrumb t('my.meals.edit')
  end

  def create
    @meal = Meal.new meal_params
    if @meal.save
      redirect_to :my_meals, notice: t('my.meals.saved')
    else
      render :new
    end
  end

  def update
    @meal.update meal_params
    if @meal.save
      redirect_to :my_meals, notice: t('my.meals.saved')
    else
      add_breadcrumb 'Modifier'
      render :edit
    end
  end

  def destroy
    @meal.destroy
    redirect_to my_meals_path, notice: 'Repas annulé'
  end

  private

  def meal_params
    params.require(:meal)
          .permit(:date, :capacity, :confirmed, :description, :formula)
          .merge({host_id: current_user.id})
  end
end

app/controllers/my/messages_controller.rb
class My::MessagesController < My::ApplicationController
  add_breadcrumb I18n.t('my.messages.name'), :my_messages_path

  def index
    @conversations = current_user.conversations
  end

  def user
    @user = User.find_by(slug: params[:user_slug])
    @conversation = Conversation.between(current_user, @user)
    @conversation.mark_as_read_by!(current_user) unless @conversation.nil?
    @message = Message.new(from: current_user)
    add_breadcrumb @user
  end

  def create
    @user = User.find_by(slug: params[:user_slug])
    @conversation = Conversation.between(current_user, @user)
    if @conversation.nil?
      @conversation = Conversation.create
      @conversation.users << current_user
      @conversation.users << @user
    end
    @message = Message.new(message_params)
    @message.conversation = @conversation
    if @message.save
      redirect_to my_conversation_path(user_slug: @user.slug), notice: 'Message bien envoyé.'
    else
      redirect_to my_conversation_path(user_slug: @user.slug), notice: 'Erreur lors de l\'envoi du message'
    end
  end

  private

  def message_params
    params.require(:message).permit(:from_id, :content)
  end
end

app/controllers/my/profile_controller.rb
class My::ProfileController < My::ApplicationController
  add_breadcrumb I18n.t('my.profile.name')

  def index
    @user = current_user
  end

  def update
    @user = current_user
    @user.assign_attributes(user_params)
    if @user.valid?(:update_profile)
      @user.save
      redirect_to :my_profile, notice: t('my.profile.saved')
    else
      render :index
    end
  end

  private

  def user_params
    params[:user][:reception_days] ||= []
    params.require(:user).permit(:first_name, :last_name, :email, :slug, :address, :zipcode, :city_id,
                                 :description, :photo, :specialties, :identity_card, reception_days: [])
  end
end

app/controllers/my/reviews_controller.rb
class My::ReviewsController < My::ApplicationController
  add_breadcrumb I18n.t('my.reviews.name')

  def index
    @conversations = current_user.conversations
  end

  def save
    @user = User.find_by(slug: params[:user_slug])
    @review = current_user.review_about(@user)
    @review.text = params[:user_review][:text]
    @review.approved = false
    @review.save
    redirect_to my_reviews_path, notice: t('my.reviews.saved')
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/my/meals/_form.html.erb
<%= simple_form_for [:my, @meal], 
                    wrapper: :horizontal_form,
                    wrapper_mappings: {
                      date: :horizontal_multi_select,
                      datetime: :horizontal_multi_select } do |f| %>
  <%= f.input   :date,
                html5: true,
                as: :date,
                label: 'Date',
                input_html: { min: Date.tomorrow } %>
  <%= f.input   :capacity,
                label: 'Nombre de convives' %>
  <%= f.input   :confirmed,
                label: 'Nombre de convives confirmés' %>
  <%= f.input   :formula,
                label: 'Formule',
                collection: Meal.formulas.map { |key, value| [t("formulas.#{key}"), key]},
                include_blank: false %>
  <%= f.input   :description %>
  <%= f.button  :submit,
                'Valider',
                class: 'btn-default' %>
<% end %>

app/views/my/meals/edit.html.erb
<%= content_for :title, t('my.meals.edit') %>
<div class="container">
	<%= render 'my/nav' %>
</div>
<div class="container-fluid bg-user-profil">
	<div class="container">
		<div class="row">
			<div class="user-profil col-md-11 offset-md-1">
				<h2><%= t('my.meals.edit') %></h2>
				<%= render 'form', meal: @meal %>
			</div>
		</div>
	</div>
</div>

app/views/my/meals/index.html.erb
<%= content_for :title, t('my.meals.name') %>
<%= render 'my/nav' %>
<%= render 'my/container' %>
  <h2><%= t('my.meals.name') %></h2>
  <%= link_to 'Proposer un repas', new_my_meal_path, class: 'btn btn-primary btn-default' %>
  <div class="table-responsive table-body">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Places totales</th>
          <th scope="col">Convives confirmés</th>
          <th scope="col">Places disponibles</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <% @meals.each do |meal| %>
      <tbody>
        <tr>
          <td><%= l meal.date, format: :day unless meal.date.nil?%></td>
          <td><%= meal.capacity %></td>
          <td><%= meal.confirmed %></td>
          <td><%= meal.remaining %></td>
          <td> <%= link_to 'Modifier', edit_my_meal_path(meal), class: 'btn btn-primary btn-update' %>
            <%= link_to 'Annuler ce repas',
            my_meal_path(meal),
            method: :delete,
            data: { confirm: 'Attention, l\'annulation est définitive' },
          class: 'btn btn-danger btn-red' %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
<%= render 'my/container_end' %>

app/views/my/meals/new.html.erb
<%= content_for :title, t('my.meals.new') %>
<div class="container">
	<%= render 'my/nav' %>
</div>
<div class="container-fluid bg-user-profil">
	<div class="container">
		<div class="row">
			<div class="user-profil col-md-11 offset-md-1">
				<h2><%= t('my.meals.new') %></h2>
				<%= render 'form', meal: @meal %>
			</div>
		</div>
	</div>
</div>