config/routes.rb
Rails.application.routes.draw do
  devise_for  :users

  namespace 'admin' do
    resources 'ambassadorships'
    resources 'cities' do
      member do
        get 'ambassadors'
        get 'guests'
        get 'hosts'
        get 'preregistrations'
      end
    end
    resources 'users' do
      collection do
        get 'admins'
        get 'ambassadors'
        get 'hosts'
        get 'guests'
        get 'search'
      end
    end
    get 'preregistrations' => 'preregistrations#index'
    post 'preregistrations' => 'preregistrations#import'
    root to: 'dashboard#index'
  end

  namespace 'my' do
    get 'messages' => 'messages#index'
    get 'messages/:user_slug' => 'messages#user', as: :conversation
    post 'messages/:user_slug' => 'messages#create', as: :send_message
    get 'profile' => 'profile#index'
    put 'profile' => 'profile#update'
    get 'reviews' => 'reviews#index'
    post 'reviews/:user_slug' => 'reviews#save', as: :review
    patch 'reviews/:user_slug' => 'reviews#save'
    resources 'meals'
    root to: 'dashboard#index'
  end

  namespace 'my_cities' do
    scope ':city_slug' do
      scope 'users' do
        get 'approval' => 'users#approval', as: :users_approval
        get 'hosts' => 'users#hosts', as: :users_hosts
        post ':user_slug/approve' => 'users#approve', as: :user_approve
        post ':user_slug/unapprove' => 'users#unapprove', as: :user_unapprove
        root to: 'users#index', as: :users
      end
      scope 'reviews' do
        get 'approval' => 'reviews#approval', as: :reviews_approval
        post ':id/approve' => 'reviews#approve', as: :review_approve
        post ':id/unapprove' => 'reviews#unapprove', as: :review_unapprove
        root to: 'reviews#index', as: :reviews
      end
    end
    root to: 'application#index'
  end

  post 'preregistrations' => 'preregistrations#create'
  get 'users/:user_slug' => 'users#show', as: :user
  get 'hosts' => 'hosts#index'
  get 'hosts/:city_slug' => 'hosts#city', as: :city_hosts
  get 'ambassadors' => 'ambassadors#index'
  get 'press' => 'pages#press'
  get 'who' => 'pages#who'
  get 'legal' => 'pages#legal'
  root to: 'pages#index'
end

app/controllers/my_cities/application_controller.rb
class MyCities::ApplicationController < ApplicationController
  before_action :redirect_if_unauthorized
  before_action :load_city

  def index
    @cities = current_user.managed_cities
    render 'my_cities/index'
  end

  protected

  def load_city
    @city = City.find_by(slug: params[:city_slug])
    add_breadcrumb I18n.t('my_cities.name'), :my_cities_root_path
    add_breadcrumb @city unless @city.nil?
  end

  def redirect_if_unauthorized
    redirect_to :root unless can? :manage, :city
  end
end

app/controllers/my_cities/reviews_controller.rb
class MyCities::ReviewsController < MyCities::ApplicationController
  def index
    @reviews = @city.reviews.page params[:page]
    add_breadcrumb t('my_cities.reviews.name')
  end

  def approval
    @reviews = @city.reviews.unapproved.page params[:page]
    add_breadcrumb t('my_cities.reviews.to_approve')
  end

  def approve
    @review = User::Review.find params[:id]
    @review.approved = true
    @review.save
    flash[:notice] = 'Avis approuvé'
    redirect_to my_cities_reviews_approval_path(city_slug: params[:city_slug])
  end

  def unapprove
    @review = User::Review.find params[:id]
    @review.approved = false
    @review.save
    flash[:notice] = 'Avis désapprouvé'
    redirect_to my_cities_reviews_path(city_slug: params[:city_slug])
  end
end

app/controllers/my_cities/users_controller.rb
class MyCities::UsersController < MyCities::ApplicationController

  def index
    @users = @city.users.guests.page params[:page]
    add_breadcrumb t('my_cities.users.guests')
  end

  def hosts
    @users = @city.users.hosts.page params[:page]
    add_breadcrumb t('my_cities.users.hosts')
  end

  def approval
    @users = @city.users.to_approve
    add_breadcrumb t('my_cities.users.to_approve')
  end

  def approve
    @user = User.find_by slug: params[:user_slug]
    if !@user.nil? && @user.city.in?(current_user.managed_cities)
      @user.approved = true
      @user.save
      flash[:notice] = 'Utilisateur approuvé'
    else
      flash[:notice] = 'Problème technique'
    end
    redirect_to my_cities_users_approval_path(city_slug: params[:city_slug])
  end

  def unapprove
    @user = User.find_by slug: params[:user_slug]
    if !@user.nil? && @user.city.in?(current_user.managed_cities)
      @user.approved = false
      @user.save
      flash[:notice] = 'Utilisateur désapprouvé'
    else
      flash[:notice] = 'Problème technique'
    end
    redirect_to my_cities_root_path
  end
end

app/views/my_cities/index.html.erb
<%= content_for :title, t('my_cities.name') %>

<div class="container">
  <h1 class="text-center mb-5"><%= t('my_cities.name') %></h1>

  <% if @cities.none? %>
    <p>Pas de ville gérée.</p>
  <% end %>

  <% @cities.each do |city| %>
    <hr/>
    <h2><%= city %></h2>
    <% classes = 'btn btn-primary btn-sm float-right' %>
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h1><%= city.users.guests.count %></h1>
          <p><%= t 'my_cities.users.guests' %></p>
          <%= link_to 'Voir la liste', my_cities_users_path(city_slug: city.slug), class: classes %>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h1><%= city.users.hosts.count %></h1>
          <p><%= t 'my_cities.users.hosts' %></p>
          <%= link_to 'Voir la liste', my_cities_users_hosts_path(city_slug: city.slug), class: classes %>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h1><%= city.users.to_approve.count %></h1>
          <p><%= t 'my_cities.users.to_approve' %></p>
          <%= link_to 'Voir la liste', my_cities_users_approval_path(city_slug: city.slug), class: classes %>
        </div>
      </div>
    </div>
    <div class="card-deck">
      <div class="card">
        <div class="card-body">
          <h1><%= city.reviews.count %></h1>
          <p><%= t('my_cities.reviews.name') %></p>
          <%= link_to 'Voir la liste', my_cities_reviews_path(city_slug: city.slug), class: classes %>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h1><%= city.reviews.unapproved.count %></h1>
          <p><%= t('my_cities.reviews.to_approve') %></p>
          <%= link_to 'Voir la liste', my_cities_reviews_approval_path(city_slug: city.slug), class: classes %>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h1><%= city.conversations.count %></h1>
          <p>Conversations</p>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h1><%= city.meals.opened.count %></h1>
          <p>Repas ouvert</p>
        </div>
      </div>
    </div>
  <% end %>
</div>