config/routes.rb
Rails.application.routes.draw do
  devise_for  :users

  namespace 'admin' do
    resources 'ambassadorships'
    resources 'cities' do
      member do
        get 'ambassadors'
        get 'guests'
        get 'hosts'
        get 'preregistrations'
      end
    end
    resources 'users' do
      collection do
        get 'admins'
        get 'ambassadors'
        get 'hosts'
        get 'guests'
        get 'search'
      end
    end
    get 'preregistrations' => 'preregistrations#index'
    post 'preregistrations' => 'preregistrations#import'
    root to: 'dashboard#index'
  end

  namespace 'my' do
    get 'messages' => 'messages#index'
    get 'messages/:user_slug' => 'messages#user', as: :conversation
    post 'messages/:user_slug' => 'messages#create', as: :send_message
    get 'profile' => 'profile#index'
    put 'profile' => 'profile#update'
    get 'reviews' => 'reviews#index'
    post 'reviews/:user_slug' => 'reviews#save', as: :review
    patch 'reviews/:user_slug' => 'reviews#save'
    resources 'meals'
    root to: 'dashboard#index'
  end

  namespace 'my_cities' do
    scope ':city_slug' do
      scope 'users' do
        get 'approval' => 'users#approval', as: :users_approval
        get 'hosts' => 'users#hosts', as: :users_hosts
        post ':user_slug/approve' => 'users#approve', as: :user_approve
        post ':user_slug/unapprove' => 'users#unapprove', as: :user_unapprove
        root to: 'users#index', as: :users
      end
      scope 'reviews' do
        get 'approval' => 'reviews#approval', as: :reviews_approval
        post ':id/approve' => 'reviews#approve', as: :review_approve
        post ':id/unapprove' => 'reviews#unapprove', as: :review_unapprove
        root to: 'reviews#index', as: :reviews
      end
    end
    root to: 'application#index'
  end

  post 'preregistrations' => 'preregistrations#create'
  get 'users/:user_slug' => 'users#show', as: :user
  get 'hosts' => 'hosts#index'
  get 'hosts/:city_slug' => 'hosts#city', as: :city_hosts
  get 'ambassadors' => 'ambassadors#index'
  get 'press' => 'pages#press'
  get 'who' => 'pages#who'
  get 'legal' => 'pages#legal'
  root to: 'pages#index'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    authorize! :read, :Dashboard
    @active_cities = City.active
    @inactive_cities = City.inactive
  end
end

app/controllers/my/dashboard_controller.rb
class My::DashboardController < My::ApplicationController
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard/activity_helper.rb
module Dashboard::ActivityHelper
end

app/helpers/dashboard/advices_helper.rb
module Dashboard::AdvicesHelper
end

app/helpers/dashboard/application_helper.rb
module Dashboard::ApplicationHelper
end

app/helpers/dashboard/messages_helper.rb
module Dashboard::MessagesHelper
end

app/helpers/dashboard/open_meals_helper.rb
module Dashboard::OpenMealsHelper
end

app/helpers/dashboard/profile_helper.rb
module Dashboard::ProfileHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/partials/_activity.html.erb
<h3>Votre activité</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

app/views/dashboard/partials/_advices.html.erb
<h3>Vos avis</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

app/views/dashboard/partials/_messages.html.erb
<h3>Vos messages</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

app/views/dashboard/partials/_nav.html.erb
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <%= link_to "VOTRE PROFIL", dashboard_profile_path, class: "nav-item nav-link #{'active' if controller_name == 'profile'}" %>

    <% if current_user.ambassador? %>
      <%= link_to "VOTRE ACTIVITÉ", dashboard_activity_path, class: "nav-item nav-link #{'active' if controller_name == 'activity'}" %>
    <% end %>

    <%= link_to "VOS MESSAGES", dashboard_messages_path, class: "nav-item nav-link #{'active' if controller_name == 'messages'}" %>
    <%= link_to "VOS AVIS", dashboard_advices_path, class: "nav-item nav-link #{'active' if controller_name == 'advices'}" %>

    <% if can? :create, :meals %>
      <%= link_to "VOS REPAS OUVERTS", dashboard_open_meals_path, class: "nav-item nav-link #{'active' if controller_name == 'open_meals'}" %>
    <% end %>
  </div>
</nav>

app/views/dashboard/partials/_open-meals.html.erb
<h3>Vos repas ouverts</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

app/views/dashboard/partials/_profile.html.erb
<h3>Votre profil</h3>

<%= simple_form_for(@user, url: update_profile_path, html: { class: "dashboard_edit_profile", method: :post }, wrapper: :vertical_form) do |f| %>
  <div class="row">
    <div class="col col-md-4">
      <%= f.input :photo %>
      <%= image_tag @user.photo.variant(resize: "200x200^") if @user.photo.attached? %>
    </div>

    <div class="col col-md-8">
      <p><strong>Statut du profil</strong> : <%= @user.profile_status %></p>
      <%= f.association :city, include_blank: false %>
      <%= f.input :description %>

      <% if @user.guest? %>
        <%= f.input :identity_card, as: :file %>
      <% end %>

      <% if @user.host? %>
        <%= f.input :specialties, as: :text %>
        <div class="reception_days">
          <%= f.input :reception_days, as: :check_boxes, collection: [["0", 'Lundi'], ["1", 'Mardi'], ["2", 'Mercredi'], ["3", 'Jeudi'], ["4", 'Vendredi'], ["5", 'Samedi'], ["6", 'Dimanche']], label_method: :second, value_method: :first, include_hidden: false, checked: @user.reception_days %>
        </div>
      <% end %>
      <%= f.submit %>
    </div>
  </div>
<% end %>