config/routes.rb
Rails.application.routes.draw do
  devise_for  :users

  namespace 'admin' do
    resources 'ambassadorships'
    resources 'cities' do
      member do
        get 'ambassadors'
        get 'guests'
        get 'hosts'
        get 'preregistrations'
      end
    end
    resources 'users' do
      collection do
        get 'admins'
        get 'ambassadors'
        get 'hosts'
        get 'guests'
        get 'search'
      end
    end
    get 'preregistrations' => 'preregistrations#index'
    post 'preregistrations' => 'preregistrations#import'
    root to: 'dashboard#index'
  end

  namespace 'my' do
    get 'messages' => 'messages#index'
    get 'messages/:user_slug' => 'messages#user', as: :conversation
    post 'messages/:user_slug' => 'messages#create', as: :send_message
    get 'profile' => 'profile#index'
    put 'profile' => 'profile#update'
    get 'reviews' => 'reviews#index'
    post 'reviews/:user_slug' => 'reviews#save', as: :review
    patch 'reviews/:user_slug' => 'reviews#save'
    resources 'meals'
    root to: 'dashboard#index'
  end

  namespace 'my_cities' do
    scope ':city_slug' do
      scope 'users' do
        get 'approval' => 'users#approval', as: :users_approval
        get 'hosts' => 'users#hosts', as: :users_hosts
        post ':user_slug/approve' => 'users#approve', as: :user_approve
        post ':user_slug/unapprove' => 'users#unapprove', as: :user_unapprove
        root to: 'users#index', as: :users
      end
      scope 'reviews' do
        get 'approval' => 'reviews#approval', as: :reviews_approval
        post ':id/approve' => 'reviews#approve', as: :review_approve
        post ':id/unapprove' => 'reviews#unapprove', as: :review_unapprove
        root to: 'reviews#index', as: :reviews
      end
    end
    root to: 'application#index'
  end

  post 'preregistrations' => 'preregistrations#create'
  get 'users/:user_slug' => 'users#show', as: :user
  get 'hosts' => 'hosts#index'
  get 'hosts/:city_slug' => 'hosts#city', as: :city_hosts
  get 'ambassadors' => 'ambassadors#index'
  get 'press' => 'pages#press'
  get 'who' => 'pages#who'
  get 'legal' => 'pages#legal'
  root to: 'pages#index'
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id              :bigint(8)        not null, primary key
#  from_id         :bigint(8)
#  content         :text
#  read_at         :datetime
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  conversation_id :integer
#

class Message < ApplicationRecord
  belongs_to :from, class_name: "User"
  belongs_to :conversation, touch: true

  scope :received_from, -> (user) { where(from_id: user.id) }
  scope :read, -> { where.not(read_at: nil) }
  scope :unread, -> { where(read_at: nil) }

  after_create :send_mail

  def to
    return if conversation.nil?
    conversation.users.where.not(id: from).first
  end

  def mark_as_read_by!(user)
    if self.read_at.nil?
      self.read_at = DateTime.now
      save
    end
  end

  def to_s
    "#{content}"
  end

  protected

  def send_mail
    MessageMailer.with(from: from, to: to).notification_email.deliver_later
  end
end

app/controllers/my/application_controller.rb
class My::ApplicationController < ApplicationController
  add_breadcrumb I18n.t('my.name'), :my_root_path

  before_action :authenticate_user!
end

app/controllers/my/dashboard_controller.rb
class My::DashboardController < My::ApplicationController
  def index
  end
end

app/controllers/my/meals_controller.rb
class My::MealsController < My::ApplicationController
  load_and_authorize_resource

  add_breadcrumb I18n.t('my.meals.name'), :my_meals_path

  def index
    @meals = current_user.meals.future
  end

  def new
    add_breadcrumb t('my.meals.new')
    @meal = Meal.new capacity: 2, confirmed: 1, date: Date.tomorrow
  end

  def edit
    add_breadcrumb t('my.meals.edit')
  end

  def create
    @meal = Meal.new meal_params
    if @meal.save
      redirect_to :my_meals, notice: t('my.meals.saved')
    else
      render :new
    end
  end

  def update
    @meal.update meal_params
    if @meal.save
      redirect_to :my_meals, notice: t('my.meals.saved')
    else
      add_breadcrumb 'Modifier'
      render :edit
    end
  end

  def destroy
    @meal.destroy
    redirect_to my_meals_path, notice: 'Repas annulé'
  end

  private

  def meal_params
    params.require(:meal)
          .permit(:date, :capacity, :confirmed, :description, :formula)
          .merge({host_id: current_user.id})
  end
end

app/controllers/my/messages_controller.rb
class My::MessagesController < My::ApplicationController
  add_breadcrumb I18n.t('my.messages.name'), :my_messages_path

  def index
    @conversations = current_user.conversations
  end

  def user
    @user = User.find_by(slug: params[:user_slug])
    @conversation = Conversation.between(current_user, @user)
    @conversation.mark_as_read_by!(current_user) unless @conversation.nil?
    @message = Message.new(from: current_user)
    add_breadcrumb @user
  end

  def create
    @user = User.find_by(slug: params[:user_slug])
    @conversation = Conversation.between(current_user, @user)
    if @conversation.nil?
      @conversation = Conversation.create
      @conversation.users << current_user
      @conversation.users << @user
    end
    @message = Message.new(message_params)
    @message.conversation = @conversation
    if @message.save
      redirect_to my_conversation_path(user_slug: @user.slug), notice: 'Message bien envoyé.'
    else
      redirect_to my_conversation_path(user_slug: @user.slug), notice: 'Erreur lors de l\'envoi du message'
    end
  end

  private

  def message_params
    params.require(:message).permit(:from_id, :content)
  end
end

app/controllers/my/profile_controller.rb
class My::ProfileController < My::ApplicationController
  add_breadcrumb I18n.t('my.profile.name')

  def index
    @user = current_user
  end

  def update
    @user = current_user
    @user.assign_attributes(user_params)
    if @user.valid?(:update_profile)
      @user.save
      redirect_to :my_profile, notice: t('my.profile.saved')
    else
      render :index
    end
  end

  private

  def user_params
    params[:user][:reception_days] ||= []
    params.require(:user).permit(:first_name, :last_name, :email, :slug, :address, :zipcode, :city_id,
                                 :description, :photo, :specialties, :identity_card, reception_days: [])
  end
end

app/controllers/my/reviews_controller.rb
class My::ReviewsController < My::ApplicationController
  add_breadcrumb I18n.t('my.reviews.name')

  def index
    @conversations = current_user.conversations
  end

  def save
    @user = User.find_by(slug: params[:user_slug])
    @review = current_user.review_about(@user)
    @review.text = params[:user_review][:text]
    @review.approved = false
    @review.save
    redirect_to my_reviews_path, notice: t('my.reviews.saved')
  end
end

app/helpers/dashboard/messages_helper.rb
module Dashboard::MessagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/my/messages/_message.html.erb
<div class="message <%= message.from == current_user ? 'message--from-me' : 'message--from-someone-else' %>">
  <div class="message-from-date">
    <p><%= link_to message.from, user_path(user_slug: message.from.slug) %> - <%= l message.created_at, format: :short %></p>
  </div>
  <div class="message-content">
    <p><%= simple_format message.content %></p>
    <span class="badge badge-primary">
      <% if message.read_at.nil? %>
      <%= t('my.messages.not_read') %>
      <% else %>
      <%= t('my.messages.read_on', date: l(message.read_at, format: :long)) %>
      <% end %>
    </span>
  </div>
</div>

app/views/my/messages/index.html.erb
<%= content_for :title, t('my.messages.name') %>
<%= render 'my/nav' %>
<%= render 'my/container' %>
  <h2><%= t('my.messages.name') %></h2>
  <ul class="list-unstyled message-line">
    <% @conversations.each do |conversation| %>
      <% user = conversation.other(current_user).first %>
      <% next if user.nil? # Deleted user %>
      <li>
        <div class="row">
          <div class="col-md-9">
            <%= link_to my_conversation_path(user_slug: user.slug) do %>
              <%= render 'users/user_small', user: user %>
            <% end %>
            <p class="message"><%= simple_format user.description %></p>
          </div>
          <div class="col-md-3 date">
            <time><%= l conversation.updated_at, format: :short_day %></time>
            <% unread_count = conversation.messages.unread.received_from(user).count %>
            <% if unread_count > 0 %>
              <span class="badge badge-primary">
                <%= unread_count %> message<%= 's' if unread_count > 1 %> non lu<%= 's' if unread_count > 1 %>
              </span>
            <% end %>
          </div>
        </div>
        <hr/>
      </li>
    <% end %>
  </ul>
  <h3><%= t 'my.messages.contact_my_ambassadors' %></h3>
  <ul class="list-unstyled message-line-2">
    <% current_user.city.ambassadors.each do |user| %>
    <li>
      <%= link_to my_conversation_path(user_slug: user.slug) do %>
        <%= render 'users/user_small', user: user %>
      <% end %>
    </li>
    <% end unless current_user.city.nil? %>
  </ul>
<%= render 'my/container_end' %>

app/views/my/messages/user.html.erb
<% title = "#{t('my.messages.conversation_with')} #{@user}" %>
<%= content_for :title, title %>
<%= render 'my/nav' %>
<%= render 'my/container' %>
  <h2>
    <%= t('my.messages.conversation_with') %>
    <%= link_to @user, user_path(user_slug: @user.slug) %>
  </h2>
  <div class="conversation">
    <div class="row">
      <div class="col-lg-2 col-4">
        <%= link_to user_path(user_slug: @user.slug) do %>
          <% if @user.photo.attached? %>
            <%= image_tag @user.photo.variant(resize: '60x60^', combine_options: { gravity: 'center', crop: '60x60+0+0' }), class: 'img-fluid img-user img-user-3' %>
          <% else %>
            <%= image_tag 'avatar.png', class: 'img-fluid img-user img-user-3' %>
          <% end %>
        <% end %>
        <%= render 'users/approved', user: @user %>
      </div>
      <div class="col-lg-10">
        <% if @conversation %>
          <% @conversation.messages.each do |message| %>
            <%= render 'message', message: message %>
          <% end %>
        <% else %>
          <p><%= t('my.messages.no_messages') %></p>
        <% end %>
      </div>
    </div>
  </div>

  <% if current_user.host? %>
    <div class="row collapse show conversation__conversion">
      <div class="col-lg-6 offset-lg-6">
        <h3>Êtes-vous tombés d'accord sur un repas ?</h3>
        <%= simple_form_for [:my, Meal.new(host: current_user, capacity: 1, confirmed: 1, date: Date.tomorrow)] do |f| %>
          <%= f.input :host_id, as: :hidden %>
          <%= f.input :capacity, as: :hidden %>
          <%= f.input :confirmed, as: :hidden %>
          <%= f.input :date, as: :hidden %>
          <a href="#" class="btn btn-primary btn-sm" data-toggle="collapse" data-target=".conversation__conversion">Non, pas encore</a>
          <%= f.submit 'Oui', class: 'btn btn-primary btn-sm' %>
          <%= link_to 'Oui, mais il manque des convives', new_my_meal_path, class: 'btn btn-primary btn-sm' %>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= simple_form_for @message, url: my_send_message_path(user_slug: @user.slug) do |f| %>
    <%= f.input :from_id, as: :hidden %>
    <%= f.input :content, label: false, placeholder: t('my.messages.type_your_message') %>
    <%= f.button :submit, t('my.messages.send'), class: 'btn-default' %>
  <% end %>
  <div class="previous">
    <a href="<%= my_messages_path %>"><i class="fas fa-angle-double-left"></i> Revenir aux messages</a>
  </div>
<%= render 'my/container_end' %>